### ISSUE TITLE
ManageSuccess and ManageError reset ALL conditions in Status?!

### ISSUE THREAD

**Issue by tomqwpl** [redhat-cop/operator-utils#26]
OK, this is super unexpected.
I've been trying for a long time to figure out why the conditions I've been using to record the state of my reconciliation process always seem to go missing. Eventually I realised that ManageSuccess and ManageError have the effect of wiping all conditions, via a call to SetReconcileStatus. This should be using things like status.RemoveCondition, status.SetCondition and so on to ensure that other condition instances don't get altered.

**Comment by raffaelespazzoli** [comment]
@tomqwpl you are probably right. I admit I don't fully understand how status conditions work and my implementation is probably clumsy. Would you be able to send me a PR as a proposal of how to improve this?
