### ISSUE TITLE
Question on initialization, error and validation handling.

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/operator-utils#52]
From https://github.com/redhat-cop/operator-utils#managing-cr-validation and https://github.com/redhat-cop/operator-utils/blob/master/api/v1alpha1/mycrd_types.go#L31 the `Initialized`, `Valid` and `Error` fields are on the actual CRD. Isn't that a bit strange as they then look like input-fields on the CR (and required by default) - don't these rather belong on the `Status` sub-resource?

**Comment by raffaelespazzoli** [comment]
that CRD is supposed to help test the functionalities of `BaseReconciler`, in particular initialization ,validation and error management. The idea is that you will create that CR, then toggle the flags and watch the operator behavior, possibly during a demo.

**Comment by davidkarlsen** [comment]
OK - not obvious from the code/wording in the readme.
Thanks for the answer!
