### ISSUE TITLE
ManageErrorWithRequeue Requeue is ignored

### ISSUE THREAD

**Issue by Athosone** [redhat-cop/operator-utils#63]
Hi !

I am using your library as it helps a lot.
```
github.com/redhat-cop/operator-utils v1.1.2
```
However I face an issue with ManageErrorWithRequeue

It does re queue but not it does not take into account the re queue after which seems "normal" considering the code of the reconcile function.

If there is an error it re schedule into the loop immediately.

```
	// RunInformersAndControllers the syncHandler, passing it the namespace/Name string of the
	// resource to be synced.
	if result, err := c.Do.Reconcile(ctx, req); err != nil {
		c.Queue.AddRateLimited(req)
		ctrlmetrics.ReconcileErrors.WithLabelValues(c.Name).Inc()
		ctrlmetrics.ReconcileTotal.WithLabelValues(c.Name, "error").Inc()
		log.Error(err, "Reconciler error")
		return
	} else if result.RequeueAfter > 0 {
		// The result.RequeueAfter request will be lost, if it is returned
		// along with a non-nil error. But this is intended as
		// We need to drive to stable reconcile loops before queuing due
		// to result.RequestAfter
		c.Queue.Forget(obj)
		c.Queue.AddAfter(req, result.RequeueAfter)
		ctrlmetrics.ReconcileTotal.WithLabelValues(c.Name, "requeue_after").Inc()
		return
	} else if result.Requeue {
		c.Queue.AddRateLimited(req)
		ctrlmetrics.ReconcileTotal.WithLabelValues(c.Name, "requeue").Inc()
		return
	}
```

Am I missing something?

Regards,

**Comment by raffaelespazzoli** [comment]
@davidkarlsen I think you were the last to work on this function. Can you comment on the question from @Athosone ?

**Comment by davidkarlsen** [comment]
I did some refactoring but the logic was not altered.

AFAIR the controller runtime will reschedule immediately if you return an error, see: https://www.openshift.com/blog/kubernetes-operators-best-practices "Managing errors".

https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Result
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/reconcile/reconcile.go#L89

**Comment by Athosone** [comment]
Yeah that's the point,

Why does the method accept a duration in that case as the duration will be ignored anyway?

**Comment by davidkarlsen** [comment]
https://github.com/redhat-cop/operator-utils/pull/50#issuecomment-751721506

but it's more related to the controller-runtime - without using the operator-utils you could still set a requeueAfter delay, and return a non-nil err. If the err is non-nil it would be rescheduled immediately. Hope this helps.

**Comment by Athosone** [comment]
Yes that what I ended up to do.

I get confused by the name of the method as it takes an error as parameter.

I thought it would use the err.Error() for the message and then return nil for the error parameter in order to take into account the requeueAfter parameter.


Thanks for taking the time.
