### ISSUE TITLE
Vulnerability with protobuf v.1.3.1

### ISSUE THREAD

**Issue by Athosone** [redhat-cop/operator-utils#67]
Hi !

There is a vulnerability with the version of gogo protobuf v1.3.1.

From what I saw the controller runtime is aware and will fix it in version v0.9.0.

https://github.com/kubernetes-sigs/controller-runtime/issues/1473

Are you planning on updating this repo when its out ?

I can do a PR once they release it to bump the version if you don't see any conflict with your library.

Regards,

Ayrton

**Comment by raffaelespazzoli** [comment]
Please do that. We try to stay aligned with operator-sdk.

**Comment by Athosone** [comment]
I created the PR if you got time to check it

**Comment by raffaelespazzoli** [comment]
On vacation now. I saw the pr, it's a ton of changes. Anyway we can do it
via kubebuilder? Aren't they having the same issue?

**Comment by Athosone** [comment]
Sorry I am not sure to understand your intent.

As for kubebuilder they did not move to 0.9.0 yet
https://github.com/kubernetes-sigs/kubebuilder

**Comment by Athosone** [comment]
Ok looks like kubebuilder moved to 0.9.0,

I'll will continue to use my fork while you update the library.

**Comment by Athosone** [comment]
I am closing it as it seems resolved
